# Ultraquick Tutorial
[numpy_ultraquick_tutorial](https://colab.research.google.com/github/google/eng-edu/blob/main/ml/cc/exercises/numpy_ultraquick_tutorial.ipynb?utm_source=mlcc&utm_campaign=colab-external&utm_medium=referral&utm_content=numpy_tf2-colab&hl=en#scrollTo=tYjvXmvFPoPB)

In [1]:
import numpy as np

In [2]:
one_dimensional_array = np.array([1.2, 2.4, 3.5, 4.7, 6.1, 7.2, 8.3, 9.5])
print(one_dimensional_array)

[1.2 2.4 3.5 4.7 6.1 7.2 8.3 9.5]


In [3]:
two_dimensional_array = np.array([[6, 5], [11, 7], [4, 8]])
print(two_dimensional_array)

[[ 6  5]
 [11  7]
 [ 4  8]]


In [4]:
sequence_of_integers = np.arange(5, 12)
print(sequence_of_integers)

[ 5  6  7  8  9 10 11]


In [5]:
random_integers_between_50_and_100 = np.random.randint(low=50,high=101,size=7)
print(random_integers_between_50_and_100)

[60 52 63 54 63 87 70]


In [6]:
random_floats_between_0_and_1 = np.random.random([6])
print(random_floats_between_0_and_1)

[0.69349745 0.23512699 0.40459645 0.71149889 0.70619233 0.60974385]


In [7]:
random_floats_between_2_and_3 = random_floats_between_0_and_1 + 2.0
print(random_floats_between_2_and_3)

[2.69349745 2.23512699 2.40459645 2.71149889 2.70619233 2.60974385]


In [8]:
random_integers_between_150_and_300 = random_integers_between_50_and_100 * 3
print(random_integers_between_150_and_300)

[180 156 189 162 189 261 210]


## Create a linear dataset

In [9]:
feature = np.arange(6, 21)
print(feature)

[ 6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [10]:
label = (3 * feature) + 4
print(label)

[22 25 28 31 34 37 40 43 46 49 52 55 58 61 64]


In [11]:
noise = (np.random.random([15]) * 4) - 2 # Float between -2 and 2
print(noise)

[-1.69255633  0.95278343 -0.48589041  0.25448119 -1.15237641 -1.53515354
  0.9282458  -1.37046733 -1.33428868  0.56137359 -1.04634561  0.15139504
  1.52572804 -1.77764557  0.28577937]


In [12]:
label = label + noise # add some noise to the label
print(label)

[20.30744367 25.95278343 27.51410959 31.25448119 32.84762359 35.46484646
 40.9282458  41.62953267 44.66571132 49.56137359 50.95365439 55.15139504
 59.52572804 59.22235443 64.28577937]
